version: "3"
services:
   backend:
     build: ./backend
     ports:
       - "3000:3000"
     depends_on:
       - mongo
     networks:
       - mynet
   mongo:
     image: mongo
     volumes:
       - mongo-data:/data/db
     networks:
       - mynet
volumes:
   mongo-data:
networks:
   mynet:
